#!/bin/bash
ruby_location=ftp://ftp.ruby-lang.org/pub/ruby/
ruby_file=ruby-1.8.7-p334.tar.gz
#ruby_location=http://ftp.ruby-lang.org/pub/ruby/1.9/
#ruby_file=ruby-1.9.2-p180.tar.gz
rubygems_location=http://production.cf.rubygems.org/rubygems/
rubygems_file=rubygems-1.7.2.tgz

# CentOS prerequisites
sudo yum install -y gcc zlib-devel readline-devel openssl-devel openssl make || exit 1

curl -o $ruby_file $ruby_location$ruby_file
tar xvfz $ruby_file
cd ${ruby_file%.tar.gz}
./configure
make
sudo make install
cd ext/openssl
ruby extconf.rb
make
sudo make install
cd ../../..

curl -L -o $rubygems_file $rubygems_location$rubygems_file
tar xvfz $rubygems_file
cd ${rubygems_file%.tgz}
sudo ruby setup.rb
