#!/bin/bash
git_location=http://fossies.org/unix/misc/
git_file=git-1.7.6.1.tar.gz

# CentOS prerequisites
yum install -y curl-devel

curl -o $git_file $git_location$git_file
tar xvfz $git_file
cd ${git_file%.tar.gz}
./configure
make
make install
cd ..